exp_setting:
  exp_name: 'ACM'                         # Experiment title, log/checkpoint files will be named after this
  checkpoint_dir: './checkpoint/'         # Folder for model checkpoints
  log_dir: './log/'                       # Folder for training logs
  data_root: '../datasets/'
  seed: 9
  n_nodes: 4019
  input_dim: 256
  mp_1: 'PAP'
  mp_2: 'PSP'
  mp_3: 'APA'
  mp_4: 'APSPA'


model:
  vae:
    encoder: [['fc', 128, '', 'LeakyReLU', 0.2],
              ['fc', 64, 'bn', 'LeakyReLU', 0.2]
             ]
    decoder: [['fc', 128, 'bn', 'LeakyReLU', 0.2, True],
              ['fc', 256, '', 'LeakyReLU', 0.2, False]
             ]
    lr: 0.01
    betas: [0.5, 0.999]

  D_mp:
    dnn: [['fc', 32, '', 'LeakyReLU', 0.2],
          ['fc', 32, '', 'LeakyReLU', 0.2],
          ['fc', 2, 'bn', 'LeakyReLU', 0.2]
         ]
    lr: 0.01
    betas: [0.5, 0.999]

  D:
    dnn: [['fc', 128, '', 'LeakyReLU', 0.2],
          ['fc', [1,2], '', 'LeakyReLU', 0.2]
         ]
    lr: 0.01
    betas: [0.5, 0.999]


trainer:
  total_step: 20000
  batch_size: 32

  lambda:
    reconstruct:
      init:  20000
      final: 1
      step:  10000
    kl:
      init:  0.00001
      final: 0.00001
      step:  1
    adv_mp_clf:
      init:  0
      final: 1
      step:  5000
    gp:
      init: 100
      final: 100
      step: 1
    d_adv:
      init: 0
      final: 0.001
      step: 100
    d_clf:
      init: 0
      final: 0.001
      step: 100

  verbose_step: 20
  save_log: True
  save_checkpoint: True
  save_best_only: True
